inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Gemspec/RequiredRubyVersion:
  Enabled: false
